# Generated by Django 6.0 on 2026-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='amount_crypto',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
