# Generated by Django 6.0 on 2026-02-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaccion_amount_crypto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitud de Recuperación',
                'verbose_name_plural': 'Solicitudes de Recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
