# Generated by Django 6.0 on 2026-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_profile_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
